// filepath: c:\Users\najla\Desktop\2290 Project Folder\frontend\app\layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* --- Website Banner --- */}
        <div
          style={{
            textAlign: "center",
            margin: 0,
            padding: "20px 0 6px 0",
            background: "#fff",
            borderBottom: "2px solid #d32f2f",
          }}
        >
          <h1 style={{ margin: 0, color: "#d32f2f", fontWeight: 700, fontSize: "2.1rem", letterSpacing: 0.5 }}>
            Website Under Development!
          </h1>
          <div style={{ fontWeight: 500, marginTop: -4, fontSize: "1.1rem", color: "#222" }}>
            By Majd Consulting, PLLC
          </div>
        </div>

        {/* --- Navigation Bar --- */}
        <nav
          style={{
            display: "flex",
            alignItems: "center",
            gap: 24,
            padding: "0 32px",
            height: 48,
            background: "#fff",
            borderBottom: "1px solid #eee",
            fontSize: "1.1rem",
            fontWeight: 500,
            marginBottom: 24,
          }}
        >
          <a href="/" style={{ color: "#222", textDecoration: "none" }}>Home</a>
          <a href="/profile" style={{ color: "#222", textDecoration: "none" }}>My Filings</a>
        </nav>

        {/* --- Main Content --- */}
        {children}
      </body>
    </html>
  );
}